version: '3.8'

services:
  user-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_service_db
    volumes:
      - user-db-data:/var/lib/mysql
    networks:
      - epharma-network

  inventory-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory_db
    volumes:
      - inventory-db-data:/var/lib/mysql
    networks:
      - epharma-network

  order-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_db
    volumes:
      - order-db-data:/var/lib/mysql
    networks:
      - epharma-network

  user-service:
    build: ./user_service
    depends_on:
      - user-db
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=user-db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=user_service_db
    networks:
      - epharma-network

  inventory-service:
    build: ./inventory_service
    depends_on:
      - inventory-db
    ports:
      - "5002:5002"
    environment:
      - DB_HOST=inventory-db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=inventory_db
    networks:
      - epharma-network

  order-service:
    build: ./order_service
    depends_on:
      - order-db
      - inventory-service
    ports:
      - "5003:5003"
    environment:
      - DB_HOST=order-db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=order_db
    networks:
      - epharma-network

  api-gateway:
    build: ./api_gateway
    ports:
      - "5000:5000"
    depends_on:
      - user-service
      - inventory-service
      - order-service
    networks:
      - epharma-network

networks:
  epharma-network:

volumes:
  user-db-data:
  inventory-db-data:
  order-db-data: